{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {}
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 9: Define Action Group Schema"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# OpenAPI schema for action group\n",
    "action_group_schema = {\n",
    "    \"openapi\": \"3.0.0\",\n",
    "    \"info\": {\n",
    "        \"title\": \"Product API\",\n",
    "        \"description\": \"API for interacting with product information and inventory\",\n",
    "        \"version\": \"1.0.0\"\n",
    "    },\n",
    "    \"paths\": {\n",
    "        \"/getProductDetails\": {\n",
    "            \"get\": {\n",
    "                \"summary\": \"Get product details\",\n",
    "                \"description\": \"Retrieve details about a specific product or all products\",\n",
    "                \"parameters\": [\n",
    "                    {\n",
    "                        \"name\": \"productId\",\n",
    "                        \"in\": \"query\",\n",
    "                        \"description\": \"ID of the product to retrieve (optional)\",\n",
    "                        \"required\": False,\n",
    "                        \"schema\": {\n",
    "                            \"type\": \"string\"\n",
    "                        }\n",
    "                    }\n",
    "                ],\n",
    "                \"responses\": {\n",
    "                    \"200\": {\n",
    "                        \"description\": \"Successful operation\",\n",
    "                        \"content\": {\n",
    "                            \"application/json\": {\n",
    "                                \"schema\": {\n",
    "                                    \"type\": \"object\",\n",
    "                                    \"properties\": {\n",
    "                                        \"statusCode\": {\"type\": \"integer\"},\n",
    "                                        \"product\": {\"type\": \"object\"},\n",
    "                                        \"products\": {\"type\": \"array\"}\n",
    "                                    }\n",
    "                                }\n",
    "                            }\n",
    "                        }\n",
    "                    },\n",
    "                    \"404\": {\n",
    "                        \"description\": \"Product not found\"\n",
    "                    }\n",
    "                }\n",
    "            }\n",
    "        },\n",
    "        \"/checkInventory\": {\n",
    "            \"get\": {\n",
    "                \"summary\": \"Check product inventory\",\n",
    "                \"description\": \"Check availability and stock levels for a specific product\",\n",
    "                \"parameters\": [\n",
    "                    {\n",
    "                        \"name\": \"productId\",\n",
    "                        \"in\": \"query\",\n",
    "                        \"description\": \"ID of the product to check\",\n",
    "                        \"required\": True,\n",
    "                        \"schema\": {\n",
    "                            \"type\": \"string\"\n",
    "                        }\n",
    "                    },\n",
    "                    {\n",
    "                        \"name\": \"location\",\n",
    "                        \"in\": \"query\",\n",
    "                        \"description\": \"Warehouse location (optional)\",\n",
    "                        \"required\": False,\n",
    "                        \"schema\": {\n",
    "                            \"type\": \"string\"\n",
    "                        }\n",
    "                    }\n",
    "                ],\n",
    "                \"responses\": {\n",
    "                    \"200\": {\n",
    "                        \"description\": \"Successful operation\",\n",
    "                        \"content\": {\n",
    "                            \"application/json\": {\n",
    "                                \"schema\": {\n",
    "                                    \"type\": \"object\",\n",
    "                                    \"properties\": {\n",
    "                                        \"statusCode\": {\"type\": \"integer\"},\n",
    "                                        \"inventory\": {\"type\": \"object\"}\n",
    "                                    }\n",
    "                                }\n",
    "                            }\n",
    "                        }\n",
    "                    },\n",
    "                    \"404\": {\n",
    "                        \"description\": \"Product not found\"\n",
    "                    }\n",
    "                }\n",
    "            }\n",
    "        },\n",
    "        \"/placeOrder\": {\n",
    "            \"post\": {\n",
    "                \"summary\": \"Place a product order\",\n",
    "                \"description\": \"Place an order for a specific product\",\n",
    "                \"parameters\": [\n",
    "                    {\n",
    "                        \"name\": \"productId\",\n",
    "                        \"in\": \"query\",\n",
    "                        \"description\": \"ID of the product to order\",\n",
    "                        \"required\": True,\n",
    "                        \"schema\": {\n",
    "                            \"type\": \"string\"\n",
    "                        }\n",
    "                    },\n",
    "                    {\n",
    "                        \"name\": \"quantity\",\n",
    "                        \"in\": \"query\",\n",
    "                        \"description\": \"Quantity to order\",\n",
    "                        \"required\": False,\n",
    "                        \"schema\": {\n",
    "                            \"type\": \"integer\",\n",
    "                            \"default\": 1\n",
    "                        }\n",
    "                    }\n",
    "                ],\n",
    "                \"requestBody\": {\n",
    "                    \"required\": False,\n",
    "                    \"content\": {\n",
    "                        \"application/json\": {\n",
    "                            \"schema\": {\n",
    "                                \"type\": \"object\",\n",
    "                                \"properties\": {\n",
    "                                    \"customerInfo\": {\n",
    "                                        \"type\": \"object\",\n",
    "                                        \"properties\": {\n",
    "                                            \"name\": {\"type\": \"string\"},\n",
    "                                            \"email\": {\"type\": \"string\"},\n",
    "                                            \"address\": {\"type\": \"string\"}\n",
    "                                        }\n",
    "                                    }\n",
    "                                }\n",
    "                            }\n",
    "                        }\n",
    "                    }\n",
    "                },\n",
    "                \"responses\": {\n",
    "                    \"200\": {\n",
    "                        \"description\": \"Order placed successfully\",\n",
    "                        \"content\": {\n",
    "                            \"application/json\": {\n",
    "                                \"schema\": {\n",
    "                                    \"type\": \"object\",\n",
    "                                    \"properties\": {\n",
    "                                        \"statusCode\": {\"type\": \"integer\"},\n",
    "                                        \"order\": {\"type\": \"object\"}\n",
    "                                    }\n",
    "                                }\n",
    "                            }\n",
    "                        }\n",
    "                    },\n",
    "                    \"400\": {\n",
    "                        \"description\": \"Invalid input\"\n",
    "                    }\n",
    "                }\n",
    "            }\n",
    "        }\n",
    "    }\n",
    "}\n",
    "\n",
    "# Save the schema to a temporary file\n",
    "with open('/tmp/action_group_schema.json', 'w') as f:\n",
    "    json.dump(action_group_schema, f)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 10: Create Action Group for the Agent"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create an action group\n",
    "try:\n",
    "    action_group_response = bedrock_agent.create_agent_action_group(\n",
    "        actionGroupName=ACTION_GROUP_NAME,\n",
    "        description='Actions for interacting with product information and inventory',\n",
    "        apiSchema={\n",
    "            'payload': json.dumps(action_group_schema)\n",
    "        },\n",
    "        actionGroupExecutor={\n",
    "            'lambda': lambda_arn\n",
    "        }\n",
    "    )\n",
    "    action_group_id = action_group_response['agentActionGroup']['agentActionGroupId']\n",
    "    print(f\"Created action group with ID: {action_group_id}\")\n",
    "    \n",
    "except bedrock_agent.exceptions.ConflictException as e:\n",
    "    # List existing action groups\n",
    "    action_groups = bedrock_agent.list_agent_action_groups(filters={\n",
    "        'actionGroupName': {\n",
    "            'equals': ACTION_GROUP_NAME\n",
    "        }\n",
    "    })['agentActionGroupSummaries']\n",
    "    \n",
    "    if action_groups:\n",
    "        action_group_id = action_groups[0]['agentActionGroupId']\n",
    "        print(f\"Using existing action group with ID: {action_group_id}\")\n",
    "        \n",
    "        # Update the existing action group\n",
    "        bedrock_agent.update_agent_action_group(\n",
    "            agentActionGroupId=action_group_id,\n",
    "            description='Actions for interacting with product information and inventory',\n",
    "            apiSchema={\n",
    "                'payload': json.dumps(action_group_schema)\n",
    "            },\n",
    "            actionGroupExecutor={\n",
    "                'lambda': lambda_arn\n",
    "            }\n",
    "        )\n",
    "        print(f\"Updated action group: {action_group_id}\")\n",
    "    else:\n",
    "        raise Exception(\"Conflict creating action group, but couldn't find existing one\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 11: Create the Bedrock Agent"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a Bedrock agent\n",
    "try:\n",
    "    agent_response = bedrock_agent.create_agent(\n",
    "        agentName=AGENT_NAME,\n",
    "        description='An agent that provides product information, checks inventory, and processes orders',\n",
    "        instruction='You are a helpful product assistant. Use the knowledge base to provide detailed information about products. When asked about inventory or orders, use the appropriate API actions.',\n",
    "        foundationModel=MODEL_ID,\n",
    "        customerEncryptionKeyArn=None,  # Use AWS-managed key\n",
    "        idleSessionTTLInSeconds=1800  # 30 minutes\n",
    "    )\n",
    "    agent_id = agent_response['agent']['agentId']\n",
    "    print(f\"Created agent with ID: {agent_id}\")\n",
    "    \n",
    "except bedrock_agent.exceptions.ServiceQuotaExceededException:\n",
    "    # If quota exceeded, try to find an existing agent\n",
    "    agents = bedrock_agent.list_agents(filters={\n",
    "        'agentName': {\n",
    "            'equals': AGENT_NAME\n",
    "        }\n",
    "    })['agentSummaries']\n",
    "    \n",
    "    if agents:\n",
    "        agent_id = agents[0]['agentId']\n",
    "        print(f\"Using existing agent with ID: {agent_id}\")\n",
    "    else:\n",
    "        raise Exception(\"Service quota exceeded and couldn't find existing agent\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 12: Associate Action Group and Knowledge Base with the Agent"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Associate action group with agent\n",
    "try:\n",
    "    bedrock_agent.associate_agent_action_group(\n",
    "        agentId=agent_id,\n",
    "        agentVersion='DRAFT',\n",
    "        actionGroupId=action_group_id,\n",
    "        skipResourceInUseCheck=True\n",
    "    )\n",
    "    print(f\"Associated action group {action_group_id} with agent {agent_id}\")\n",
    "except Exception as e:\n",
    "    print(f\"Error associating action group: {e}\")\n",
    "\n",
    "# Associate knowledge base with agent\n",
    "try:\n",
    "    bedrock_agent.associate_agent_knowledge_base(\n",
    "        agentId=agent_id,\n",
    "        agentVersion='DRAFT',\n",
    "        knowledgeBaseId=kb_id,\n",
    "        description='Product information knowledge base',\n",
    "        skipResourceInUseCheck=True\n",
    "    )\n",
    "    print(f\"Associated knowledge base {kb_id} with agent {agent_id}\")\n",
    "except Exception as e:\n",
    "    print(f\"Error associating knowledge base: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 13: Prepare and Deploy the Agent"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Prepare and Deploy the agent\n",
    "try:\n",
    "    # Prepare the agent\n",
    "    prepare_response = bedrock_agent.prepare_agent(\n",
    "        agentId=agent_id,\n",
    "        agentVersion='DRAFT'\n",
    "    )\n",
    "    print(f\"Agent preparation status: {prepare_response['preparationStatus']}\")\n",
    "    \n",
    "    # Wait for preparation to complete\n",
    "    max_attempts = 20\n",
    "    attempts = 0\n",
    "    status = prepare_response['preparationStatus']\n",
    "    \n",
    "    while status == 'IN_PROGRESS' and attempts < max_attempts:\n",
    "        time.sleep(5)\n",
    "        attempts += 1\n",
    "        \n",
    "        status_response = bedrock_agent.get_agent(\n",
    "            agentId=agent_id,\n",
    "            agentVersion='DRAFT'\n",
    "        )\n",
    "        status = status_response['agent']['preparationStatus']\n",
    "        print(f\"Preparation status: {status} (Attempt {attempts}/{max_attempts})\")\n",
    "        \n",
    "        if status in ['COMPLETE', 'FAILED']:\n",
    "            break\n",
    "    \n",
    "    if status == 'COMPLETE':\n",
    "        print(\"Agent preparation completed successfully!\")\n",
    "        \n",
    "        # Create a new version of the agent\n",
    "        version_response = bedrock_agent.create_agent_version(\n",
    "            agentId=agent_id,\n",
    "            agentVersion='DRAFT'\n",
    "        )\n",
    "        version_number = version_response['agentVersion']\n",
    "        print(f\"Created agent version: {version_number}\")\n",
    "        \n",
    "        # Create an alias pointing to the new version\n",
    "        try:\n",
    "            alias_response = bedrock_agent.create_agent_alias(\n",
    "                agentId=agent_id,\n",
    "                agentAliasName='prod',\n",
    "                description='Production alias',\n",
    "                routingConfiguration=[\n",
    "                    {\n",
    "                        'agentVersion': version_number,\n",
    "                        'provisionedThroughput': None  # Use on-demand throughput\n",
    "                    }\n",
    "                ]\n",
    "            )\n",
    "            alias_id = alias_response['agentAlias']['agentAliasId']\n",
    "            print(f\"Created agent alias: {alias_id}\")\n",
    "        except bedrock_agent.exceptions.ConflictException:\n",
    "            # Update existing alias\n",
    "            aliases = bedrock_agent.list_agent_aliases(\n",
    "                agentId=agent_id,\n",
    "                filters={\n",
    "                    'agentAliasName': {\n",
    "                        'equals': 'prod'\n",
    "                    }\n",
    "                }\n",
    "            )['agentAliasSummaries']\n",
    "            \n",
    "            if aliases:\n",
    "                alias_id = aliases[0]['agentAliasId']\n",
    "                bedrock_agent.update_agent_alias(\n",
    "                    agentId=agent_id,\n",
    "                    agentAliasId=alias_id,\n",
    "                    routingConfiguration=[\n",
    "                        {\n",
    "                            'agentVersion': version_number,\n",
    "                            'provisionedThroughput': None  # Use on-demand throughput\n",
    "                        }\n",
    "                    ]\n",
    "                )\n",
    "                print(f\"Updated agent alias: {alias_id} to version {version_number}\")\n",
    "            else:\n",
    "                print(\"Couldn't find existing alias to update\")\n",
    "    else:\n",
    "        print(f\"Agent preparation failed with status: {status}\")\n",
    "        \n",
    "except Exception as e:\n",
    "    print(f\"Error preparing or deploying agent: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 14: Test the Agent"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to invoke the agent\n",
    "def invoke_agent(message):\n",
    "    try:\n",
    "        # Get the alias ID for invoking the agent\n",
    "        aliases = bedrock_agent.list_agent_aliases(\n",
    "            agentId=agent_id,\n",
    "            filters={\n",
    "                'agentAliasName': {\n",
    "                    'equals': 'prod'\n",
    "                }\n",
    "            }\n",
    "        )['agentAliasSummaries']\n",
    "        \n",
    "        if not aliases:\n",
    "            return \"Error: No agent alias found\"\n",
    "        \n",
    "        alias_id = aliases[0]['agentAliasId']\n",
    "        \n",
    "        # Generate a session ID if needed\n",
    "        session_id = str(uuid.uuid4())\n",
    "        \n",
    "        response = bedrock_agent_runtime.invoke_agent(\n",
    "            agentId=agent_id,\n",
    "            agentAliasId=alias_id,\n",
    "            sessionId=session_id,\n",
    "            inputText=message\n",
    "        )\n",
    "        \n",
    "        # Extract the response\n",
    "        chunks = []\n",
    "        for event in response.get('chunk', {}).get('bytes'):\n",
    "            chunk = json.loads(event.decode('utf-8'))\n",
    "            if 'chunk' in chunk and 'content' in chunk['chunk']:\n",
    "                chunks.append(chunk['chunk']['content'][0]['text'])\n",
    "        \n",
    "        return ''.join(chunks)\n",
    "    \n",
    "    except Exception as e:\n",
    "        return f\"Error invoking agent: {str(e)}\"\n",
    "\n",
    "# Test the agent with some queries\n",
    "test_queries = [\n",
    "    \"Tell me about the Premium Coffee Maker\",\n",
    "    \"What products do you have in stock?\",\n",
    "    \"I want to buy the Air Fryer Deluxe. Is it available?\",\n",
    "    \"Place an order for the Stand Mixer Elite\"\n",
    "]\n",
    "\n",
    "# Run the test queries\n",
    "for query in test_queries:\n",
    "    print(f\"\\nQuery: {query}\")\n",
    "    response = invoke_agent(query)\n",
    "    print(f\"Response: {response}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Summary of What We've Done\n",
    "\n",
    "In this notebook, we've created a complete Bedrock Agent that can:\n",
    "\n",
    "1. Access product information from a knowledge base (stored in S3)\n",
    "2. Perform actions through a Lambda function to:\n",
    "   - Get product details\n",
    "   - Check inventory\n",
    "   - Place orders\n",
    "\n",
    "This demonstrates a complete end-to-end workflow for creating and using a Bedrock Agent that combines knowledge base retrieval and API actions to provide intelligent responses and perform tasks."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 15: Clean Up Resources (Optional)\n",
    "\n",
    "If you want to clean up the resources created in this notebook, you can use the code below. Be careful as this will permanently delete resources."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Only run this cell if you want to clean up resources\n",
    "# Set this to True to enable cleanup\n",
    "ENABLE_CLEANUP = False\n",
    "\n",
    "if ENABLE_CLEANUP:\n",
    "    print(\"Starting cleanup...\")\n",
    "    \n",
    "    # Delete the agent alias\n",
    "    try:\n",
    "        aliases = bedrock_agent.list_agent_aliases(\n",
    "            agentId=agent_id,\n",
    "            filters={\n",
    "                'agentAliasName': {\n",
    "                    'equals': 'prod'\n",
    "                }\n",
    "            }\n",
    "        )['agentAliasSummaries']\n",
    "        \n",
    "        if aliases:\n",
    "            alias_id = aliases[0]['agentAliasId']\n",
    "            bedrock_agent.delete_agent_alias(\n",
    "                agentId=agent_id,\n",
    "                agentAliasId=alias_id\n",
    "            )\n",
    "            print(f\"Deleted agent alias: {alias_id}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error deleting agent alias: {e}\")\n",
    "    \n",
    "    # Disassociate action group and knowledge base\n",
    "    try:\n",
    "        bedrock_agent.disassociate_agent_action_group(\n",
    "            agentId=agent_id,\n",
    "            agentVersion='DRAFT',\n",
    "            actionGroupId=action_group_id\n",
    "        )\n",
    "        print(f\"Disassociated action group from agent\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error disassociating action group: {e}\")\n",
    "        \n",
    "    try:\n",
    "        bedrock_agent.disassociate_agent_knowledge_base(\n",
    "            agentId=agent_id,\n",
    "            agentVersion='DRAFT',\n",
    "            knowledgeBaseId=kb_id\n",
    "        )\n",
    "        print(f\"Disassociated knowledge base from agent\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error disassociating knowledge base: {e}\")\n",
    "    \n",
    "    # Delete the agent\n",
    "    try:\n",
    "        bedrock_agent.delete_agent(\n",
    "            agentId=agent_id,\n",
    "            skipResourceInUseCheck=True\n",
    "        )\n",
    "        print(f\"Deleted agent: {agent_id}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error deleting agent: {e}\")\n",
    "    \n",
    "    # Delete the action group\n",
    "    try:\n",
    "        bedrock_agent.delete_agent_action_group(\n",
    "            agentActionGroupId=action_group_id\n",
    "        )\n",
    "        print(f\"Deleted action group: {action_group_id}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error deleting action group: {e}\")\n",
    "    \n",
    "    # Delete the Lambda function\n",
    "    try:\n",
    "        lambda_client.delete_function(\n",
    "            FunctionName=LAMBDA_FUNCTION_NAME\n",
    "        )\n",
    "        print(f\"Deleted Lambda function: {LAMBDA_FUNCTION_NAME}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error deleting Lambda function: {e}\")\n",
    "    \n",
    "    # Delete the data source\n",
    "    try:\n",
    "        bedrock_agent.delete_data_source(\n",
    "            knowledgeBaseId=kb_id,\n",
    "            dataSourceId=data_source_id\n",
    "        )\n",
    "        print(f\"Deleted data source: {data_source_id}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error deleting data source: {e}\")\n",
    "    \n",
    "    # Delete the knowledge base\n",
    "    try:\n",
    "        bedrock_agent.delete_knowledge_base(\n",
    "            knowledgeBaseId=kb_id\n",
    "        )\n",
    "        print(f\"Deleted knowledge base: {kb_id}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error deleting knowledge base: {e}\")\n",
    "    \n",
    "    # Delete objects in S3 bucket\n",
    "    try:\n",
    "        objects = s3.list_objects_v2(Bucket=BUCKET_NAME)\n",
    "        if 'Contents' in objects:\n",
    "            for obj in objects['Contents']:\n",
    "                s3.delete_object(Bucket=BUCKET_NAME, Key=obj['Key'])\n",
    "                print(f\"Deleted S3 object: {obj['Key']}\")\n",
    "                \n",
    "        # Delete the S3 bucket\n",
    "        s3.delete_bucket(Bucket=BUCKET_NAME)\n",
    "        print(f\"Deleted S3 bucket: {BUCKET_NAME}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error deleting S3 bucket or objects: {e}\")\n",
    "    \n",
    "    # Note: We're not deleting the IAM roles as they might be used by other resources\n",
    "    print(\"Cleanup completed.\")\n",
    "else:\n",
    "    print(\"Cleanup skipped. Set ENABLE_CLEANUP = True to enable resource cleanup.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Additional Resources\n",
    "\n",
    "- [Amazon Bedrock Documentation](https://docs.aws.amazon.com/bedrock/)\n",
    "- [Amazon Bedrock Agents Documentation](https://docs.aws.amazon.com/bedrock/latest/userguide/agents.html)\n",
    "- [Amazon Bedrock Knowledge Bases Documentation](https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-bases.html)\n",
    "- [AWS Lambda Documentation](https://docs.aws.amazon.com/lambda/)\n",
    "- [Amazon S3 Documentation](https://docs.aws.amazon.com/s3/)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
},
   "source": [
    "# Creating an Amazon Bedrock Agent with Knowledge Base and Custom Actions\n",
    "\n",
    "This notebook demonstrates how to:\n",
    "1. Set up the necessary AWS resources\n",
    "2. Create a knowledge base\n",
    "3. Create a simple action group with a Lambda function\n",
    "4. Create and test a Bedrock Agent\n",
    "\n",
    "Prerequisites:\n",
    "- AWS account with Bedrock access\n",
    "- Appropriate IAM permissions\n",
    "- AWS CLI configured locally"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Environment Setup\n",
    "\n",
    "First, let's install and import the necessary libraries."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Install necessary packages\n",
    "!pip install boto3 pandas requests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import boto3\n",
    "import json\n",
    "import time\n",
    "import os\n",
    "import uuid\n",
    "from datetime import datetime\n",
    "\n",
    "# Create clients for various AWS services\n",
    "bedrock = boto3.client('bedrock')\n",
    "bedrock_agent = boto3.client('bedrock-agent')\n",
    "bedrock_agent_runtime = boto3.client('bedrock-agent-runtime')\n",
    "s3 = boto3.client('s3')\n",
    "lambda_client = boto3.client('lambda')\n",
    "iam = boto3.client('iam')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Configuration Variables\n",
    "\n",
    "Set up the necessary configuration variables for our resources."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Configuration\n",
    "BUCKET_NAME = 'bedrock-agent-demo-' + str(uuid.uuid4())[:8]\n",
    "KB_NAME = 'agent-knowledge-base'\n",
    "AGENT_NAME = 'product-info-agent'\n",
    "LAMBDA_FUNCTION_NAME = 'bedrock-agent-action-handler'\n",
    "ACTION_GROUP_NAME = 'product-actions'\n",
    "REGION = boto3.session.Session().region_name\n",
    "\n",
    "# Model ID for the foundation model\n",
    "MODEL_ID = 'anthropic.claude-3-sonnet-20240229-v1:0'\n",
    "\n",
    "# Sample documents for knowledge base\n",
    "SAMPLE_DOCS = [\n",
    "    {\n",
    "        'name': 'product_1.txt',\n",
    "        'content': \"\"\"Product ID: P001\n",
    "Name: Premium Coffee Maker\n",
    "Description: Automatic drip coffee maker with programmable timer and thermal carafe.\n",
    "Price: $149.99\n",
    "In Stock: Yes\n",
    "Features: 12-cup capacity, auto-shutoff, brew strength control.\n",
    "Warranty: 2 years\"\"\"\n",
    "    },\n",
    "    {\n",
    "        'name': 'product_2.txt',\n",
    "        'content': \"\"\"Product ID: P002\n",
    "Name: Smart Blender Pro\n",
    "Description: High-performance blender with digital touch interface and multiple pre-programmed settings.\n",
    "Price: $199.99\n",
    "In Stock: No (Available in 2 weeks)\n",
    "Features: 64-oz container, 5 speed settings, pulse function, dishwasher-safe parts.\n",
    "Warranty: 5 years\"\"\"\n",
    "    },\n",
    "    {\n",
    "        'name': 'product_3.txt',\n",
    "        'content': \"\"\"Product ID: P003\n",
    "Name: Air Fryer Deluxe\n",
    "Description: Digital air fryer with 6 cooking presets and non-stick basket.\n",
    "Price: $129.99\n",
    "In Stock: Yes\n",
    "Features: 5.5-quart capacity, dishwasher-safe parts, recipe book included.\n",
    "Warranty: 1 year\"\"\"\n",
    "    }\n",
    "]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 1: Create S3 Bucket for Knowledge Base Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create S3 bucket\n",
    "if REGION == 'us-east-1':\n",
    "    s3.create_bucket(Bucket=BUCKET_NAME)\n",
    "else:\n",
    "    s3.create_bucket(\n",
    "        Bucket=BUCKET_NAME,\n",
    "        CreateBucketConfiguration={'LocationConstraint': REGION}\n",
    "    )\n",
    "    \n",
    "print(f\"Created S3 bucket: {BUCKET_NAME}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 2: Upload Sample Documents to S3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Upload sample documents to S3\n",
    "for doc in SAMPLE_DOCS:\n",
    "    s3.put_object(\n",
    "        Bucket=BUCKET_NAME,\n",
    "        Key=f\"documents/{doc['name']}\",\n",
    "        Body=doc['content'],\n",
    "        ContentType='text/plain'\n",
    "    )\n",
    "    print(f\"Uploaded {doc['name']} to S3\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 3: Create IAM Role for Knowledge Base"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create IAM role for the knowledge base\n",
    "kb_trust_policy = {\n",
    "    \"Version\": \"2012-10-17\",\n",
    "    \"Statement\": [\n",
    "        {\n",
    "            \"Effect\": \"Allow\",\n",
    "            \"Principal\": {\"Service\": \"bedrock.amazonaws.com\"},\n",
    "            \"Action\": \"sts:AssumeRole\"\n",
    "        }\n",
    "    ]\n",
    "}\n",
    "\n",
    "kb_role_name = 'BedrockKnowledgeBaseRole'\n",
    "\n",
    "try:\n",
    "    # Try to create the role\n",
    "    kb_role = iam.create_role(\n",
    "        RoleName=kb_role_name,\n",
    "        AssumeRolePolicyDocument=json.dumps(kb_trust_policy)\n",
    "    )\n",
    "    kb_role_arn = kb_role['Role']['Arn']\n",
    "    print(f\"Created new IAM role: {kb_role_arn}\")\n",
    "    \n",
    "    # Attach policy to access S3\n",
    "    kb_policy = {\n",
    "        \"Version\": \"2012-10-17\",\n",
    "        \"Statement\": [\n",
    "            {\n",
    "                \"Effect\": \"Allow\",\n",
    "                \"Action\": [\n",
    "                    \"s3:GetObject\",\n",
    "                    \"s3:ListBucket\"\n",
    "                ],\n",
    "                \"Resource\": [\n",
    "                    f\"arn:aws:s3:::{BUCKET_NAME}\",\n",
    "                    f\"arn:aws:s3:::{BUCKET_NAME}/*\"\n",
    "                ]\n",
    "            }\n",
    "        ]\n",
    "    }\n",
    "    \n",
    "    kb_policy_name = 'BedrockKBPolicy'\n",
    "    iam.put_role_policy(\n",
    "        RoleName=kb_role_name,\n",
    "        PolicyName=kb_policy_name,\n",
    "        PolicyDocument=json.dumps(kb_policy)\n",
    "    )\n",
    "    print(f\"Attached policy to role: {kb_policy_name}\")\n",
    "    \n",
    "    # Wait for role to propagate\n",
    "    time.sleep(10)\n",
    "    \n",
    "except iam.exceptions.EntityAlreadyExistsException:\n",
    "    # If role already exists, get its ARN\n",
    "    kb_role_arn = iam.get_role(RoleName=kb_role_name)['Role']['Arn']\n",
    "    print(f\"Using existing IAM role: {kb_role_arn}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 4: Create a Knowledge Base for the Agent"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a knowledge base\n",
    "try:\n",
    "    kb_response = bedrock_agent.create_knowledge_base(\n",
    "        name=KB_NAME,\n",
    "        roleArn=kb_role_arn,\n",
    "        knowledgeBaseConfiguration={\n",
    "            'type': 'VECTOR',\n",
    "            'vectorKnowledgeBaseConfiguration': {\n",
    "                'embeddingModelArn': f'arn:aws:bedrock:{REGION}::foundation-model/amazon.titan-embed-text-v1'\n",
    "            }\n",
    "        },\n",
    "        description='Knowledge base for product information'\n",
    "    )\n",
    "    kb_id = kb_response['knowledgeBase']['knowledgeBaseId']\n",
    "    print(f\"Created knowledge base with ID: {kb_id}\")\n",
    "except bedrock_agent.exceptions.ServiceQuotaExceededException:\n",
    "    # If we've hit the quota, list existing KBs and use the first one\n",
    "    kbs = bedrock_agent.list_knowledge_bases()['knowledgeBaseSummaries']\n",
    "    kb_id = kbs[0]['knowledgeBaseId']\n",
    "    print(f\"Using existing knowledge base with ID: {kb_id}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 5: Create a Data Source for the Knowledge Base"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a data source for the knowledge base\n",
    "try:\n",
    "    data_source_response = bedrock_agent.create_data_source(\n",
    "        knowledgeBaseId=kb_id,\n",
    "        name='product-data-source',\n",
    "        dataSourceConfiguration={\n",
    "            'type': 'S3',\n",
    "            's3Configuration': {\n",
    "                'bucketArn': f'arn:aws:s3:::{BUCKET_NAME}',\n",
    "                'inclusionPrefixes': ['documents/']\n",
    "            }\n",
    "        },\n",
    "        description='Product information documents'\n",
    "    )\n",
    "    data_source_id = data_source_response['dataSource']['dataSourceId']\n",
    "    print(f\"Created data source with ID: {data_source_id}\")\n",
    "except Exception as e:\n",
    "    print(f\"Error creating data source: {e}\")\n",
    "    # List existing data sources\n",
    "    try:\n",
    "        data_sources = bedrock_agent.list_data_sources(knowledgeBaseId=kb_id)['dataSourceSummaries']\n",
    "        if data_sources:\n",
    "            data_source_id = data_sources[0]['dataSourceId']\n",
    "            print(f\"Using existing data source with ID: {data_source_id}\")\n",
    "        else:\n",
    "            raise Exception(\"No existing data sources found and couldn't create a new one\")\n",
    "    except Exception as inner_e:\n",
    "        print(f\"Error listing data sources: {inner_e}\")\n",
    "        raise"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 6: Start Data Ingestion for the Knowledge Base"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Start data ingestion for the knowledge base\n",
    "try:\n",
    "    ingestion_job = bedrock_agent.start_ingestion_job(\n",
    "        knowledgeBaseId=kb_id,\n",
    "        dataSourceId=data_source_id\n",
    "    )\n",
    "    ingestion_job_id = ingestion_job['ingestionJob']['ingestionJobId']\n",
    "    print(f\"Started ingestion job: {ingestion_job_id}\")\n",
    "    \n",
    "    # Wait for ingestion to complete\n",
    "    max_attempts = 30\n",
    "    attempts = 0\n",
    "    status = 'IN_PROGRESS'\n",
    "    \n",
    "    while status == 'IN_PROGRESS' and attempts < max_attempts:\n",
    "        time.sleep(10)\n",
    "        attempts += 1\n",
    "        \n",
    "        job_details = bedrock_agent.get_ingestion_job(\n",
    "            knowledgeBaseId=kb_id,\n",
    "            dataSourceId=data_source_id,\n",
    "            ingestionJobId=ingestion_job_id\n",
    "        )\n",
    "        \n",
    "        status = job_details['ingestionJob']['status']\n",
    "        print(f\"Ingestion job status: {status} (Attempt {attempts}/{max_attempts})\")\n",
    "        \n",
    "        if status in ['COMPLETE', 'FAILED', 'STOPPED']:\n",
    "            break\n",
    "    \n",
    "    if status == 'COMPLETE':\n",
    "        print(\"Ingestion job completed successfully!\")\n",
    "    else:\n",
    "        print(f\"Ingestion job status: {status}\")\n",
    "        if status == 'FAILED':\n",
    "            print(f\"Failure reason: {job_details['ingestionJob'].get('failureReason', 'Unknown')}\")\n",
    "except Exception as e:\n",
    "    print(f\"Error starting ingestion job: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 7: Create IAM Role for Lambda Function"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create IAM role for Lambda function\n",
    "lambda_trust_policy = {\n",
    "    \"Version\": \"2012-10-17\",\n",
    "    \"Statement\": [\n",
    "        {\n",
    "            \"Effect\": \"Allow\",\n",
    "            \"Principal\": {\"Service\": \"lambda.amazonaws.com\"},\n",
    "            \"Action\": \"sts:AssumeRole\"\n",
    "        }\n",
    "    ]\n",
    "}\n",
    "\n",
    "lambda_role_name = 'BedrockAgentLambdaRole'\n",
    "\n",
    "try:\n",
    "    # Create Lambda execution role\n",
    "    lambda_role = iam.create_role(\n",
    "        RoleName=lambda_role_name,\n",
    "        AssumeRolePolicyDocument=json.dumps(lambda_trust_policy)\n",
    "    )\n",
    "    lambda_role_arn = lambda_role['Role']['Arn']\n",
    "    print(f\"Created Lambda execution role: {lambda_role_arn}\")\n",
    "    \n",
    "    # Attach basic Lambda execution policy\n",
    "    iam.attach_role_policy(\n",
    "        RoleName=lambda_role_name,\n",
    "        PolicyArn='arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'\n",
    "    )\n",
    "    print(\"Attached Lambda basic execution policy\")\n",
    "    \n",
    "    # Wait for role to propagate\n",
    "    time.sleep(10)\n",
    "    \n",
    "except iam.exceptions.EntityAlreadyExistsException:\n",
    "    # If role already exists, get its ARN\n",
    "    lambda_role_arn = iam.get_role(RoleName=lambda_role_name)['Role']['Arn']\n",
    "    print(f\"Using existing Lambda execution role: {lambda_role_arn}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 8: Create Lambda Function for Action Group"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Lambda function code\n",
    "lambda_code = \"\"\"\n",
    "import json\n",
    "import random\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "def lambda_handler(event, context):\n",
    "    print(f\"Received event: {json.dumps(event)}\")\n",
    "    \n",
    "    # Extract action parameters\n",
    "    api_path = event.get('apiPath', '')\n",
    "    parameters = event.get('parameters', {})\n",
    "    request_body = event.get('requestBody', {})\n",
    "    \n",
    "    if api_path == '/getProductDetails':\n",
    "        return get_product_details(parameters)\n",
    "    elif api_path == '/checkInventory':\n",
    "        return check_inventory(parameters)\n",
    "    elif api_path == '/placeOrder':\n",
    "        return place_order(parameters, request_body)\n",
    "    else:\n",
    "        return {\n",
    "            'statusCode': 400,\n",
    "            'error': f\"Unknown API path: {api_path}\"\n",
    "        }\n",
    "\n",
    "def get_product_details(parameters):\n",
    "    product_id = parameters.get('productId', '')\n",
    "    \n",
    "    # Dummy product database\n",
    "    products = {\n",
    "        'P001': {\n",
    "            'id': 'P001',\n",
    "            'name': 'Premium Coffee Maker',\n",
    "            'description': 'Automatic drip coffee maker with programmable timer and thermal carafe.',\n",
    "            'price': 149.99,\n",
    "            'category': 'Kitchen Appliances',\n",
    "            'rating': 4.7,\n",
    "            'reviews': 245\n",
    "        },\n",
    "        'P002': {\n",
    "            'id': 'P002',\n",
    "            'name': 'Smart Blender Pro',\n",
    "            'description': 'High-performance blender with digital touch interface and multiple pre-programmed settings.',\n",
    "            'price': 199.99,\n",
    "            'category': 'Kitchen Appliances',\n",
    "            'rating': 4.5,\n",
    "            'reviews': 189\n",
    "        },\n",
    "        'P003': {\n",
    "            'id': 'P003',\n",
    "            'name': 'Air Fryer Deluxe',\n",
    "            'description': 'Digital air fryer with 6 cooking presets and non-stick basket.',\n",
    "            'price': 129.99,\n",
    "            'category': 'Kitchen Appliances',\n",
    "            'rating': 4.8,\n",
    "            'reviews': 302\n",
    "        },\n",
    "        'P004': {\n",
    "            'id': 'P004',\n",
    "            'name': 'Stand Mixer Elite',\n",
    "            'description': 'Professional-grade stand mixer with planetary mixing action and 10 speed settings.',\n",
    "            'price': 299.99,\n",
    "            'category': 'Kitchen Appliances',\n",
    "            'rating': 4.9,\n",
    "            'reviews': 427\n",
    "        },\n",
    "        'P005': {\n",
    "            'id': 'P005',\n",
    "            'name': 'Digital Food Scale',\n",
    "            'description': 'Precision digital food scale with tare function and multiple unit conversions.',\n",
    "            'price': 24.99,\n",
    "            'category': 'Kitchen Accessories',\n",
    "            'rating': 4.6,\n",
    "            'reviews': 178\n",
    "        }\n",
    "    }\n",
    "    \n",
    "    # If no specific product ID is provided, return all products\n",
    "    if not product_id:\n",
    "        return {\n",
    "            'statusCode': 200,\n",
    "            'products': list(products.values())\n",
    "        }\n",
    "    \n",
    "    # If product ID is provided, return specific product details\n",
    "    if product_id in products:\n",
    "        return {\n",
    "            'statusCode': 200,\n",
    "            'product': products[product_id]\n",
    "        }\n",
    "    else:\n",
    "        return {\n",
    "            'statusCode': 404,\n",
    "            'error': f\"Product with ID {product_id} not found\"\n",
    "        }\n",
    "\n",
    "def check_inventory(parameters):\n",
    "    product_id = parameters.get('productId', '')\n",
    "    location = parameters.get('location', 'Default Warehouse')\n",
    "    \n",
    "    # Dummy inventory database\n",
    "    inventory = {\n",
    "        'P001': {'quantity': 42, 'status': 'In Stock', 'nextShipment': None},\n",
    "        'P002': {'quantity': 0, 'status': 'Out of Stock', 'nextShipment': '2025-04-15'},\n",
    "        'P003': {'quantity': 15, 'status': 'In Stock', 'nextShipment': None},\n",
    "        'P004': {'quantity': 7, 'status': 'Low Stock', 'nextShipment': '2025-04-10'},\n",
    "        'P005': {'quantity': 63, 'status': 'In Stock', 'nextShipment': None}\n",
    "    }\n",
    "    \n",
    "    if not product_id:\n",
    "        return {\n",
    "            'statusCode': 400,\n",
    "            'error': \"Product ID is required\"\n",
    "        }\n",
    "    \n",
    "    if product_id in inventory:\n",
    "        result = inventory[product_id].copy()\n",
    "        result['productId'] = product_id\n",
    "        result['location'] = location\n",
    "        result['lastUpdated'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')\n",
    "        \n",
    "        return {\n",
    "            'statusCode': 200,\n",
    "            'inventory': result\n",
    "        }\n",
    "    else:\n",
    "        return {\n",
    "            'statusCode': 404,\n",
    "            'error': f\"Inventory for product {product_id} not found\"\n",
    "        }\n",
    "\n",
    "def place_order(parameters, request_body):\n",
    "    product_id = parameters.get('productId', '')\n",
    "    quantity = int(parameters.get('quantity', 1))\n",
    "    customer_info = request_body.get('customerInfo', {})\n",
    "    \n",
    "    if not product_id:\n",
    "        return {\n",
    "            'statusCode': 400,\n",
    "            'error': \"Product ID is required\"\n",
    "        }\n",
    "    \n",
    "    # Generate order details\n",
    "    order_id = f\"ORD-{random.randint(10000, 99999)}\"\n",
    "    order_date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')\n",
    "    estimated_delivery = (datetime.now() + timedelta(days=random.randint(3, 7))).strftime('%Y-%m-%d')\n",
    "    \n",
    "    return {\n",
    "        'statusCode': 200,\n",
    "        'order': {\n",
    "            'orderId': order_id,\n",
    "            'productId': product_id,\n",
    "            'quantity': quantity,\n",
    "            'customerInfo': customer_info,\n",
    "            'orderDate': order_date,\n",
    "            'status': 'Confirmed',\n",
    "            'estimatedDelivery': estimated_delivery\n",
    "        }\n",
    "    }\n",
    "\"\"\"\n",
    "\n",
    "# Create a zip file for the Lambda function\n",
    "with open('/tmp/lambda_function.py', 'w') as f:\n",
    "    f.write(lambda_code)\n",
    "\n",
    "import zipfile\n",
    "with zipfile.ZipFile('/tmp/lambda_function.zip', 'w') as z:\n",
    "    z.write('/tmp/lambda_function.py', 'lambda_function.py')\n",
    "\n",
    "# Read the zip file\n",
    "with open('/tmp/lambda_function.zip', 'rb') as f:\n",
    "    lambda_zip = f.read()\n",
    "\n",
    "    # Create or update Lambda function
    try:
        # Check if the function already exists
        lambda_function = lambda_client.get_function(FunctionName=LAMBDA_FUNCTION_NAME)
        
        # Update existing function
        lambda_client.update_function_code(
            FunctionName=LAMBDA_FUNCTION_NAME,
            ZipFile=lambda_zip
        )
        print(f"Updated Lambda function: {LAMBDA_FUNCTION_NAME}")
        
        # Get the function ARN
        lambda_arn = lambda_function['Configuration']['FunctionArn']
        
    except lambda_client.exceptions.ResourceNotFoundException:
        # Create new function
        lambda_response = lambda_client.create_function(
            FunctionName=LAMBDA_FUNCTION_NAME,
            Runtime='python3.10',
            Role=lambda_role_arn,
            Handler='lambda_function.lambda_handler',
            Code={
                'ZipFile': lambda_zip
            },
            Timeout=30
        )
        lambda_arn = lambda_response['FunctionArn']
        print(f"Created Lambda function: {lambda_arn}")
        
        # Wait for function to be ready
        time.sleep(10)